2025-01-31 11:12:28,080 1422 INFO ? odoo: Odoo version 18.0 
2025-01-31 11:12:28,080 1422 INFO ? odoo: Using configuration file at /home/ubuntu/odoo/odoo.conf 
2025-01-31 11:12:28,080 1422 INFO ? odoo: addons paths: ['/home/ubuntu/odoo/odoo/addons', '/root/.local/share/Odoo/addons/18.0', '/home/ubuntu/odoo/addons'] 
2025-01-31 11:12:28,080 1422 INFO ? odoo: database: ubuntu@localhost:5432 
2025-01-31 11:12:28,409 1422 INFO ? odoo.addons.base.models.ir_actions_report: You need Wkhtmltopdf to print a pdf version of the reports. 
2025-01-31 11:12:28,409 1422 INFO ? odoo.addons.base.models.ir_actions_report: You need Wkhtmltoimage to generate images from html. 
2025-01-31 11:12:28,740 1422 INFO ? odoo.service.server: HTTP service (werkzeug) running on ip-172-31-35-149.ec2.internal:8069 
2025-01-31 11:12:40,860 1422 INFO ? odoo.modules.loading: loading 1 modules... 
2025-01-31 11:12:40,896 1422 INFO ? odoo.modules.loading: 1 modules loaded in 0.04s, 0 queries (+0 extra) 
2025-01-31 11:12:40,915 1422 WARNING ? odoo.modules.module: Missing `license` key in manifest for 'game_cards', defaulting to LGPL-3 
2025-01-31 11:12:40,956 1422 INFO ? odoo.modules.loading: loading 13 modules... 
2025-01-31 11:12:41,788 1422 INFO ? odoo.modules.loading: 13 modules loaded in 0.83s, 0 queries (+0 extra) 
2025-01-31 11:12:41,863 1422 INFO ? odoo.modules.loading: Modules loaded. 
2025-01-31 11:12:41,879 1422 INFO ? odoo.modules.registry: Registry loaded in 1.159s 
2025-01-31 11:12:41,881 1422 INFO mydb odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-01-31 11:12:41,945 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:12:41] "GET / HTTP/1.1" 303 - 23 0.293 1.003
2025-01-31 11:12:42,147 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:12:42] "GET /odoo HTTP/1.1" 303 - 5 0.004 0.019
2025-01-31 11:12:42,415 1422 WARNING mydb odoo.modules.module: Missing `license` key in manifest for 'game_cards', defaulting to LGPL-3 
2025-01-31 11:12:42,769 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:12:42] "GET /web/login?redirect=/odoo? HTTP/1.1" 200 - 60 0.101 0.360
2025-01-31 11:12:44,933 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:12:44] "GET /web/static/src/libs/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 - 1 0.003 1.943
2025-01-31 11:12:44,958 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:12:44] "GET /web/binary/company_logo HTTP/1.1" 200 - 6 0.009 1.946
2025-01-31 11:12:44,963 1422 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/02/02f95417efee2e4f4d53f50b40116a54164c1608'
2025-01-31 11:12:44,974 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:12:44] "GET /web/assets/6c0db48/web.assets_frontend.min.css HTTP/1.1" 500 - 8 0.016 1.972
2025-01-31 11:12:45,161 1422 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/91/910ae6904f4d00cc76f2212b31ae21a3beb6c0b9'
2025-01-31 11:12:45,162 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:12:45] "GET /web/assets/05bc0bd/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 8 0.005 0.022
2025-01-31 11:12:45,365 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:12:45] "GET /web/static/img/favicon.ico HTTP/1.1" 200 - 1 0.002 0.020
2025-01-31 11:13:00,331 1422 INFO mydb odoo.addons.base.models.res_users: Login failed for db:mydb login:admin from 82.130.129.126 
2025-01-31 11:13:00,335 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:00] "POST /web/login HTTP/1.1" 200 - 13 0.009 0.644
2025-01-31 11:13:00,597 1422 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/02/02f95417efee2e4f4d53f50b40116a54164c1608'
2025-01-31 11:13:00,599 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:00] "GET /web/assets/6c0db48/web.assets_frontend.min.css HTTP/1.1" 500 - 8 0.007 0.037
2025-01-31 11:13:00,600 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:00] "GET /web/binary/company_logo HTTP/1.1" 304 - 6 0.007 0.021
2025-01-31 11:13:00,802 1422 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/91/910ae6904f4d00cc76f2212b31ae21a3beb6c0b9'
2025-01-31 11:13:00,803 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:00] "GET /web/assets/05bc0bd/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 8 0.004 0.022
2025-01-31 11:13:05,268 1422 INFO mydb odoo.addons.base.models.res_users: Login failed for db:mydb login:admin from 82.130.129.126 
2025-01-31 11:13:05,272 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:05] "POST /web/login HTTP/1.1" 200 - 10 0.009 0.638
2025-01-31 11:13:05,525 1422 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/02/02f95417efee2e4f4d53f50b40116a54164c1608'
2025-01-31 11:13:05,527 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:05] "GET /web/assets/6c0db48/web.assets_frontend.min.css HTTP/1.1" 500 - 8 0.006 0.036
2025-01-31 11:13:05,529 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:05] "GET /web/binary/company_logo HTTP/1.1" 304 - 6 0.006 0.037
2025-01-31 11:13:05,715 1422 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/91/910ae6904f4d00cc76f2212b31ae21a3beb6c0b9'
2025-01-31 11:13:05,716 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:05] "GET /web/assets/05bc0bd/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 8 0.005 0.022
2025-01-31 11:13:07,389 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/database/manager HTTP/1.1" 200 - 8 0.006 0.687
2025-01-31 11:13:07,671 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/src/libs/fontawesome/css/font-awesome.css HTTP/1.1" 200 - 1 0.001 0.066
2025-01-31 11:13:07,690 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/js/dist/util/index.js HTTP/1.1" 200 - 1 0.001 0.069
2025-01-31 11:13:07,690 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/js/dist/dom/event-handler.js HTTP/1.1" 200 - 1 0.003 0.066
2025-01-31 11:13:07,691 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/dist/css/bootstrap.css HTTP/1.1" 200 - 1 0.002 0.070
2025-01-31 11:13:07,692 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/js/dist/dom/data.js HTTP/1.1" 200 - 1 0.004 0.066
2025-01-31 11:13:07,758 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/js/dist/dom/manipulator.js HTTP/1.1" 200 - 1 0.002 0.018
2025-01-31 11:13:07,910 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/js/dist/dom/selector-engine.js HTTP/1.1" 200 - 1 0.001 0.049
2025-01-31 11:13:07,913 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/js/dist/util/config.js HTTP/1.1" 200 - 1 0.002 0.050
2025-01-31 11:13:07,914 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/js/dist/util/component-functions.js HTTP/1.1" 200 - 1 0.002 0.035
2025-01-31 11:13:07,944 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/js/dist/util/backdrop.js HTTP/1.1" 200 - 1 0.001 0.019
2025-01-31 11:13:07,961 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:07] "GET /web/static/lib/bootstrap/js/dist/util/focustrap.js HTTP/1.1" 200 - 1 0.002 0.016
2025-01-31 11:13:08,135 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:08] "GET /web/static/lib/bootstrap/js/dist/util/scrollbar.js HTTP/1.1" 200 - 1 0.003 0.050
2025-01-31 11:13:08,148 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:08] "GET /web/static/lib/bootstrap/js/dist/base-component.js HTTP/1.1" 200 - 1 0.001 0.051
2025-01-31 11:13:08,149 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:08] "GET /web/static/src/public/database_manager.js HTTP/1.1" 200 - 1 0.001 0.032
2025-01-31 11:13:08,151 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:08] "GET /web/static/lib/bootstrap/js/dist/modal.js HTTP/1.1" 200 - 1 0.001 0.049
2025-01-31 11:13:08,341 1422 INFO ? werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:08] "GET /web/static/img/logo2.png HTTP/1.1" 200 - 1 0.001 0.020
2025-01-31 11:13:11,788 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:11] "GET /odoo?db=mydb HTTP/1.1" 303 - 5 0.004 0.021
2025-01-31 11:13:12,012 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:12] "GET /web/login?redirect=/odoo?db%3Dmydb HTTP/1.1" 200 - 8 0.007 0.038
2025-01-31 11:13:12,354 1422 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/02/02f95417efee2e4f4d53f50b40116a54164c1608'
2025-01-31 11:13:12,354 1422 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/91/910ae6904f4d00cc76f2212b31ae21a3beb6c0b9'
2025-01-31 11:13:12,355 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:12] "GET /web/assets/6c0db48/web.assets_frontend.min.css HTTP/1.1" 500 - 8 0.007 0.123
2025-01-31 11:13:12,357 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:12] "GET /web/assets/05bc0bd/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 8 0.057 0.057
2025-01-31 11:13:12,359 1422 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:13:12] "GET /web/binary/company_logo HTTP/1.1" 304 - 6 0.012 0.104
2025-01-31 11:13:18,422 1422 INFO ? odoo.service.server: Initiating shutdown 
2025-01-31 11:13:18,422 1422 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-01-31 11:13:18,756 1422 INFO ? odoo.sql_db: ConnectionPool(read/write;used=0/count=0/max=64): Closed 5 connections  
2025-01-31 11:16:53,175 1566 INFO ? odoo: Odoo version 18.0 
2025-01-31 11:16:53,176 1566 INFO ? odoo: Using configuration file at /home/ubuntu/odoo/odoo.conf 
2025-01-31 11:16:53,176 1566 INFO ? odoo: addons paths: ['/home/ubuntu/odoo/odoo/addons', '/root/.local/share/Odoo/addons/18.0', '/home/ubuntu/odoo/addons'] 
2025-01-31 11:16:53,176 1566 INFO ? odoo: database: ubuntu@localhost:5432 
2025-01-31 11:16:53,302 1566 INFO ? odoo.addons.base.models.ir_actions_report: You need Wkhtmltopdf to print a pdf version of the reports. 
2025-01-31 11:16:53,303 1566 INFO ? odoo.addons.base.models.ir_actions_report: You need Wkhtmltoimage to generate images from html. 
2025-01-31 11:16:53,432 1566 INFO ? odoo.service.server: HTTP service (werkzeug) running on ip-172-31-35-149.ec2.internal:8069 
2025-01-31 11:17:01,269 1566 INFO ? odoo.modules.loading: loading 1 modules... 
2025-01-31 11:17:01,306 1566 INFO ? odoo.modules.loading: 1 modules loaded in 0.04s, 0 queries (+0 extra) 
2025-01-31 11:17:01,308 1566 WARNING ? odoo.modules.module: Missing `license` key in manifest for 'game_cards', defaulting to LGPL-3 
2025-01-31 11:17:01,312 1566 INFO ? odoo.modules.loading: loading 13 modules... 
2025-01-31 11:17:01,527 1566 INFO ? odoo.modules.loading: 13 modules loaded in 0.21s, 0 queries (+0 extra) 
2025-01-31 11:17:01,556 1566 INFO ? odoo.modules.loading: Modules loaded. 
2025-01-31 11:17:01,559 1566 INFO ? odoo.modules.registry: Registry loaded in 0.314s 
2025-01-31 11:17:01,560 1566 INFO mydb odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-01-31 11:17:01,580 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:01] "GET / HTTP/1.1" 303 - 22 0.019 0.337
2025-01-31 11:17:01,783 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:01] "GET /odoo HTTP/1.1" 303 - 5 0.004 0.020
2025-01-31 11:17:02,041 1566 WARNING mydb odoo.modules.module: Missing `license` key in manifest for 'game_cards', defaulting to LGPL-3 
2025-01-31 11:17:02,110 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:02] "GET /web/login?redirect=/odoo? HTTP/1.1" 200 - 60 0.033 0.116
2025-01-31 11:17:02,743 1566 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/02/02f95417efee2e4f4d53f50b40116a54164c1608'
2025-01-31 11:17:02,747 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:02] "GET /web/assets/6c0db48/web.assets_frontend.min.css HTTP/1.1" 500 - 8 0.008 0.408
2025-01-31 11:17:02,745 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:02] "GET /web/binary/company_logo HTTP/1.1" 304 - 6 0.009 0.392
2025-01-31 11:17:02,935 1566 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/91/910ae6904f4d00cc76f2212b31ae21a3beb6c0b9'
2025-01-31 11:17:02,936 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:02] "GET /web/assets/05bc0bd/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 8 0.006 0.022
2025-01-31 11:17:07,586 1566 INFO mydb odoo.addons.base.models.res_users: Login failed for db:mydb login:ubuntu from 82.130.129.126 
2025-01-31 11:17:07,589 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:07] "POST /web/login HTTP/1.1" 200 - 11 0.009 0.040
2025-01-31 11:17:07,876 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:07] "GET /web/binary/company_logo HTTP/1.1" 304 - 6 0.006 0.069
2025-01-31 11:17:07,878 1566 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/91/910ae6904f4d00cc76f2212b31ae21a3beb6c0b9'
2025-01-31 11:17:07,879 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:07] "GET /web/assets/05bc0bd/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 8 0.011 0.054
2025-01-31 11:17:07,881 1566 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/02/02f95417efee2e4f4d53f50b40116a54164c1608'
2025-01-31 11:17:07,882 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:07] "GET /web/assets/6c0db48/web.assets_frontend.min.css HTTP/1.1" 500 - 8 0.012 0.071
2025-01-31 11:17:25,507 1566 INFO mydb odoo.addons.base.models.res_users: Login failed for db:mydb login:ubuntu from 82.130.129.126 
2025-01-31 11:17:25,509 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:25] "POST /web/login HTTP/1.1" 200 - 9 0.007 0.039
2025-01-31 11:17:25,775 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:25] "GET /web/binary/company_logo HTTP/1.1" 304 - 6 0.005 0.054
2025-01-31 11:17:25,779 1566 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/02/02f95417efee2e4f4d53f50b40116a54164c1608'
2025-01-31 11:17:25,781 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:25] "GET /web/assets/6c0db48/web.assets_frontend.min.css HTTP/1.1" 500 - 8 0.010 0.056
2025-01-31 11:17:25,781 1566 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/91/910ae6904f4d00cc76f2212b31ae21a3beb6c0b9'
2025-01-31 11:17:25,782 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:25] "GET /web/assets/05bc0bd/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 8 0.006 0.043
2025-01-31 11:17:30,923 1566 INFO mydb odoo.addons.base.models.res_users: Login failed for db:mydb login:admin from 82.130.129.126 
2025-01-31 11:17:30,927 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:30] "POST /web/login HTTP/1.1" 200 - 11 0.007 0.640
2025-01-31 11:17:31,188 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:31] "GET /web/binary/company_logo HTTP/1.1" 304 - 6 0.004 0.039
2025-01-31 11:17:31,191 1566 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/02/02f95417efee2e4f4d53f50b40116a54164c1608'
2025-01-31 11:17:31,192 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:31] "GET /web/assets/6c0db48/web.assets_frontend.min.css HTTP/1.1" 500 - 8 0.008 0.055
2025-01-31 11:17:31,194 1566 ERROR mydb odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/odoo/http.py", line 2366, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1894, in _serve_db
    return self._transactioning(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1957, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/service/model.py", line 137, in retrying
    result = func()
             ^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 1924, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 2084, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_http.py", line 329, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/addons/web/controllers/binary.py", line 149, in content_assets
    stream = env['ir.binary']._get_stream_from(attachment, 'raw', filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 127, in _get_stream_from
    stream = self._record_to_stream(record, field_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_binary.py", line 74, in _record_to_stream
    return record._to_http_stream()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/odoo/odoo/addons/base/models/ir_attachment.py", line 797, in _to_http_stream
    stat = os.stat(stream.path)
           ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/Odoo/filestore/mydb/91/910ae6904f4d00cc76f2212b31ae21a3beb6c0b9'
2025-01-31 11:17:31,195 1566 INFO mydb werkzeug: 82.130.129.126 - - [31/Jan/2025 11:17:31] "GET /web/assets/05bc0bd/web.assets_frontend_minimal.min.js HTTP/1.1" 500 - 8 0.007 0.043
2025-01-31 11:17:38,339 1566 INFO ? odoo.service.server: Initiating shutdown 
2025-01-31 11:17:38,339 1566 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-01-31 11:17:38,659 1566 INFO ? odoo.sql_db: ConnectionPool(read/write;used=0/count=0/max=64): Closed 5 connections  
